/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_firework_virtualdesktop_AndroidSpiceActivity */

#ifndef _Included_com_firework_virtualdesktop_AndroidSpiceActivity
#define _Included_com_firework_virtualdesktop_AndroidSpiceActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_firework_virtualdesktop_AndroidSpiceActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_firework_virtualdesktop_AndroidSpiceActivity_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
