/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_firework_virtualdesktop_socket_Connector */

#ifndef _Included_com_firework_virtualdesktop_socket_Connector
#define _Included_com_firework_virtualdesktop_socket_Connector
#ifdef __cplusplus
extern "C" {
#endif
#undef com_firework_virtualdesktop_socket_Connector_CONNECT_SUCCESS
#define com_firework_virtualdesktop_socket_Connector_CONNECT_SUCCESS 0L
#undef com_firework_virtualdesktop_socket_Connector_CONNECT_IP_PORT_ERROR
#define com_firework_virtualdesktop_socket_Connector_CONNECT_IP_PORT_ERROR 1L
#undef com_firework_virtualdesktop_socket_Connector_CONNECT_PASSWORD_ERROR
#define com_firework_virtualdesktop_socket_Connector_CONNECT_PASSWORD_ERROR 2L
#undef com_firework_virtualdesktop_socket_Connector_CONNECT_UNKOWN_ERROR
#define com_firework_virtualdesktop_socket_Connector_CONNECT_UNKOWN_ERROR 3L
/*
 * Class:     com_firework_virtualdesktop_socket_Connector
 * Method:    AndroidSpicec
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_firework_virtualdesktop_socket_Connector_AndroidSpicec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
